P\AdminBundle\Entity\Article:
    type: entity
    table: article
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
 
    manyToOne:
        category:
            targetEntity: ArticleCategory
            inversedBy: articles
            joinColumn:
                name: category_id
                referencedColumnName: id
        user:
            targetEntity: P\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
    manyToMany:
        tags:
            targetEntity: ArticleTag
            inversedBy: articles
            joinTable:
                name: article_tags
                joinColumns:
                    article_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
    oneToMany:
        comments:
            targetEntity: ArticleComment
            mappedBy: article

    fields:
        title:
            type: string
            length: 255

        content:
            type: text
            length: 5000

        readCount:
            type: integer

        status:
            type: integer

        createdAt:
            type: datetime
