P\AdminBundle\Entity\ArticleCategory:
    type: entity
    table: article_category
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    oneToMany:
        articles:
            targetEntity: Article
            mappedBy: category
    fields:
        name:
            type: string
            length: 255

