P\AdminBundle\Entity\File:
    type: entity
    table: file

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        category:
            targetEntity: FileCategory
            inversedBy: files
            joinColumn:
                name: category_id
                referencedColumnName: id
            cascade:
                - persist

    manyToMany:
        tags:
            targetEntity: FileTag
            inversedBy: files
            joinTable:
                name: file_tags
                joinColumns:
                    file_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id
            cascade:
                - persist

    fields:
        filename:
            name: raw_filename
            type: string
            length: 255
        suffix:
            type: string
            length: 10
        mimeType:
            type: string
            length: 255
        md5:
            type: string
            length: 255
        size:
            type: integer
        createdAt:
            type: datetime
    lifecycleCallbacks:
        prePersist:   [ lifecycleFileUpload ]
        preUpdate:    [ lifecycleFileUpload ]
