P\AdminBundle\Entity\NotificationCategory:
    type: entity
    table: notification_category
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    oneToMany:
        notifications:
            targetEntity: Notification
            mappedBy: category
            orderBy:
                createdAt: desc

    fields:
        nkey:
            type: string
            length: 255
        name:
            type: string
            length: 255
