P\AdminBundle\Entity\Notification:
    type: entity
    table: notification
    repository: P\AdminBundle\Repository\AdminMenuRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        category:
            targetEntity: NotificationCategory
            inversedBy: notifications
            joinColumn:
                name: category_id
                referencedColumnName: id
        icon:
            targetEntity: Icon
            joinColumn:
                name: icon_id
                referencedColumnName: id

    fields:
        level:
            type: integer
        title:
            type: string
            length: 255
        message:
            type: text
            length: 5000
        status:
            type: integer
        createdAt:
            type: datetime
