P\AdminBundle\Entity\Region:
    type: entity
    table: region
    cache:
        usage : READ_ONLY
        region : padmin_region_region
    id:
        id:
            type: integer
    manyToOne:
        parent:
            targetEntity: Region
            inversedBy: childs
            joinColumn:
                name: parent_id
                referencedColumnName: id

    oneToMany:
        childs:
            targetEntity: Region
            mappedBy: parent
    fields:
        name:
            type: string
            length: 20
        type:
            type: integer

