p_homepage:
    path:     /
    defaults: { _controller: PAdminBundle:Dashboard:index }

p_admin_menu:
    resource: "@PAdminBundle/Resources/config/routing/adminmenu.yml"
    prefix:   /menu

p_admin_config:
    path:    /config
    defaults: { _controller: PAdminBundle:AdminConfig:index }

p_admin_choice_language:
    path:    /language/{locale}
    defaults: { _controller: PAdminBundle:AdminConfig:language }

p_admin_config_clear_cache:
    path:    /config/clearcache
    defaults: { _controller: PAdminBundle:AdminConfig:clearCache }

p_admin_dashboard:
    resource: "@PAdminBundle/Resources/config/routing/dashboard.yml"
    prefix:   /dashboard

p_admin_crontab:
    resource: "@PAdminBundle/Resources/config/routing/crontab.yml"
    prefix:   /crontab

p_admin_user:
    resource: "@PAdminBundle/Resources/config/routing/user.yml"
    prefix:   /user

p_admin_role:
    resource: "@PAdminBundle/Resources/config/routing/role.yml"
    prefix:   /role

p_admin_group:
    resource: "@PAdminBundle/Resources/config/routing/group.yml"
    prefix:   /group

p_admin_amqp:
    resource: "@PAdminBundle/Resources/config/routing/amqp.yml"
    prefix:   /amqp

p_notification_notification_category:
    resource: "@PAdminBundle/Resources/config/routing/notificationcategory.yml"
    prefix:   /notification_category

p_notification_notification:
    resource: "@PAdminBundle/Resources/config/routing/notification.yml"
    prefix:   /notification

p_file_file:
    resource: "@PAdminBundle/Resources/config/routing/file.yml"
    prefix:   /file

p_file_filetag:
    resource: "@PAdminBundle/Resources/config/routing/filetag.yml"
    prefix:   /filetag

p_file_filecategory:
    resource: "@PAdminBundle/Resources/config/routing/filecategory.yml"
    prefix:   /filecategory

p_file_home:
    path:     /home
    defaults: { _controller: PAdminBundle:FileHome:index }

p_article_articlecategory:
    resource: "@PAdminBundle/Resources/config/routing/articlecategory.yml"
    prefix:   /articlecategory

p_article_articletag:
    resource: "@PAdminBundle/Resources/config/routing/articletag.yml"
    prefix:   /articletag

p_article_article:
    resource: "@PAdminBundle/Resources/config/routing/article.yml"
    prefix:   /article

p_admin_articlecomment:
    resource: "@PAdminBundle/Resources/config/routing/articlecomment.yml"
    prefix:   /articlecomment

p_admin_icon:
    resource: "@PAdminBundle/Resources/config/routing/icon.yml"
    prefix:   /icon
