imports:
    - { resource: services/amqp.yml }
    - { resource: services/assetic.yml }
    - { resource: services/baidu.yml }
    - { resource: services/config.yml }
    - { resource: services/core.yml }
    - { resource: services/curl.yml }
    - { resource: services/markdown.yml }
    - { resource: services/menu.yml }
    - { resource: services/notification.yml }
    - { resource: services/paginator.yml }
    - { resource: services/twig.yml }

parameters:
    p.notification.levels: ['info', 'debug', 'warning', 'error', 'fatal']
    p.notification.status: ['隐藏', '正常']

    p.file_types:
        image: ['jpg', 'png', 'gif']
        document: ['txt', 'doc', 'docx', 'xls', 'xlsx']
        audio: ['mp4', 'mp3']

    p.article.status: ['隐藏', '显示']
