services:
    p.amqp:
        class: P\AdminBundle\Component\Amqp\Amqp
        arguments:
            - "@service_container"
            - '@p.http'
            - "@event_dispatcher"

    p.amqp.subscriber:
        class: P\AdminBundle\Component\Amqp\Listener\AMQPSubscriber
        tags:
            - {name: kernel.event_subscriber}
        arguments:
            - "@service_container"

    p.admin.config:
        class: P\AdminBundle\Component\Amqp\Config
        tags:
            - { name: p.admin.config }
