services:
    p.admin.listener.filter_route_role:
        class: P\AdminBundle\Component\Core\Listener\FilterRouteRoleListener
        arguments:
            - '@service_container'
            - '@doctrine.orm.default_entity_manager'
            - '@security.authorization_checker'
            - '@request_stack'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10000 }

    p.admin.core:
        class: P\AdminBundle\Component\Core\Core
        arguments:
            - '@service_container'
            - '@doctrine.orm.default_entity_manager'

    p.admin.core.config:
        class: P\AdminBundle\Component\Core\Config
        arguments:
            - '@service_container'
            - '@doctrine.orm.default_entity_manager'
