services:
    p.crontab:
        class: P\AdminBundle\Component\Crontab\Crontab
        arguments:
            - '@service_container'
            - '@doctrine.orm.default_entity_manager'

    p.crontab.listener:
        class: P\AdminBundle\Component\Crontab\EventListener\CrontabListener
        arguments:
            - '@service_container'
        tags:
            - { name: monolog.logger }
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 10000 }
