services:
    p.admin.menu:
        class: P\AdminBundle\Component\Menu\Menu
        arguments:
            - '@service_container'
            - '@router'
            - '@doctrine.orm.default_entity_manager'
            - '%p.admin.route%'
            - '@doctrine_cache.providers.result_cache_driver'

    p.admin.menu.subscriber:
        class: P\AdminBundle\Component\Menu\EventListener\MenuSubscriber
        arguments:
            - '@service_container'
        tags: 
            - { name: doctrine.event_subscriber }

    p.admin.menu.load.listener:
        class: P\AdminBundle\Component\Menu\EventListener\MenuLoadListener
        arguments:
            - '@service_container'
        tags: 
            - { name: kernel.event_listener, event: p.menu.load, method: onMenuLoad }
