services:
    p.paginator:
        class: P\AdminBundle\Component\Paginator\Paginator
        arguments:
            - "@service_container"
            - "@templating"
            - "@request_stack"

