security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_ADMIN
            - ROLE_MEMBER

        ROLE_MEMBER:
            - ROLE_MEMBER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern:             ^/
            form_login:
                provider:       fos_userbundle
                use_referer:    true
                use_forward:    true
                login_path:     /login
                check_path:     /login_check
                failure_path:   null
            logout:
                target:         /
            remember_me:
                key:      "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /
            anonymous:          true
               
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_profile|_wdt), role: IS_AUTHENTICATED_ANONYMOUSLY }

        # dev env
        - { path: ^/(css|js), role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/.*, roles: [ IS_AUTHENTICATED_FULLY ] }
