security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        admin:
            pattern:             ^/admin
            form_login:
                provider:       fos_userbundle
                use_referer:    true
                use_forward:    true
                login_path:     /admin/login
                check_path:     /admin/login_check
                failure_path:   null
            logout:
                path:           /admin/logout
                target:         /admin
            remember_me:
                secret:      "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /admin
            anonymous:          true

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_profile|_wdt), role: IS_AUTHENTICATED_ANONYMOUSLY }

        # dev env
        - { path: ^/(css|js), role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/.*, roles: [ IS_AUTHENTICATED_FULLY ] }


